name: architecture_templete_v2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core
  equatable: ^2.0.5

  # Network
  vexana: ^3.5.4

  # State
  flutter_riverpod: ^2.4.6

  # Config
  easy_localization: ^3.0.3

  # Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0

  # Navigation
  auto_route: ^7.8.4

  widgets:
    path: module/widgets

  gen:
    path: module/gen

# dependency_overrides:
#   cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  # flutter_gen: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: "launcher_json"
  ios: true
  image_path: "assets/app/app_icon.png"
  mind_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - asset/translations/
