name: architecture_templete_v2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core Dependencies
  kartal: ^3.5.0
  vexana: ^3.5.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.6
  json_annotation: ^4.8.1
  envied: ^0.5.1
  easy_localization: ^3.0.3

  widgets:
    path: module/widgets

# dependency_overrides:
#   cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  # flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_json"
  ios: true
  image_path: "assets/app/app_icon.png"
  mind_sdk_android: 21
  remove_alpha_ios: true

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - asset/translations/
